### ISSUE TITLE
Devnet deployment for testing airdrop flow and exercise testing. 

### ISSUE THREAD

**Issue by bobbyslife** [mithraiclabs/fusion#15]

**Comment by tomjohn1028** [comment]
- [ ] Add select network button
- [ ] Hook up network to the Anchor provider
- [ ] Hook up network to anywhere a Connection is instantiated
- [ ] Use devnet tokens from registry for conversions and calculations
- [ ] Create a devnet projects list

**Comment by tomjohn1028** [comment]
Some additional notes on devnet testing:

* There is no guarantee of a liquid spot market on Serum for the token. Currently the UI uses Serum to get the token price, so they will show up blank. Maybe we want to use Coingecko for pricing?
* You will still have to take the following steps to get an option in your wallet that will show up

1. Make sure your wallet has devnet SOL (got to trade.PsyOptions faucet page to claim some, be sure to set the network to devnet)
2. Claim some PSY from that faucet page as well
3. [OPTIONAL] Head to [initialize market page](https://trade.psyoptions.io/#/initialize-market). Again **be sure to change the network to devnet** and create whatever style option you want
4. Head to the [mint page](https://trade.psyoptions.io/#/mint). Again **be sure to change the network to devnet** and fill in the SAME EXACT parameters you had before. This will fill the option market key at the top and allow you to mint options. 
    * You can use the 12/30/2022 $1 PSY CALL market with address `Ap8vsZspKn3oGBhf166oJR5pcMcg7JS2b7TAh1yfSmg6`
5. After minting the options go back to fusion and connect your wallet.

**Comment by tomjohn1028** [comment]
![Screen Shot 2022-06-01 at 5 09 49 PM](https://user-images.githubusercontent.com/32071703/171521455-16410912-aff2-4e0d-bde1-f93c2e88424f.png)


added some liquidity on devnet Serum DEX so there's a price for PSY
