### ISSUE TITLE
Add Bottom Margin

### ISSUE THREAD

**Issue by bobbyslife** [mithraiclabs/fusion#19]
Add a Bottom Margin that's 30% vertical height

**Comment by tomjohn1028** [comment]
![Screen Shot 2022-05-31 at 1 27 50 PM](https://user-images.githubusercontent.com/32071703/171278768-3c8c9fed-3a7a-42c1-98c1-3964cb10ce19.png)

That adds an unnecessary scroll in some instances. Should that be a blanket statement for all pages?

**Comment by bobbyslife** [comment]
Let's just add 150px padding and keep it fixed. With the webpage background being the #F2F4F6
