### ISSUE TITLE
Navigation Resize

### ISSUE THREAD

**Issue by bobbyslife** [mithraiclabs/fusion#20]
- [x] Max width for the Nav contents should be 65% of page width on Desktop. With it being 100% on mobile with 10px padding.

- [ ] Fusion logo & Connect Wallet button should be sized 1/2 from current sizing.

**Comment by tomjohn1028** [comment]
@bobbyslife Making the logo and button a fixed size and half the current size, when there isn't too much on the screen, looks odd on desktop. Can I get a little bit more clear design direction on how they should scale?
