### ISSUE TITLE
4.002 PSY deducted even though only 4 PSY options are created

### ISSUE THREAD

**Issue by iurage** [mithraiclabs/fusion#61]
4.002 PSY deducted even though only 4 PSY options are created. Is this expected as a fee or something? In this case, can the fee be stated explicitly on airdrop creation page?
<img width="393" alt="Screenshot 2023-03-08 at 2 44 13 PM" src="https://user-images.githubusercontent.com/90453610/223638913-3d7f7191-3c2e-4643-a66c-8cc19b11eb83.png">

**Comment by iurage** [comment]
https://solscan.io/tx/2c5PSNhx454WH4wghag35fuTua8xtGb341PxdPfBbBx9vianbpSSdjZD6fwZLVzBCDzj9oRCQjqbuH1L9ZX193H

**Comment by parhim** [comment]
resolved after changing mint options to use the v2 instruction
