### ISSUE TITLE
Disabled button doesnt look obvious

### ISSUE THREAD

**Issue by iurage** [mithraiclabs/fusion#62]
After creating the airdrop, this button was shown "Create airdrop...".  It didn't look obvious to me that its disabled (being kinda gray/greenish), and i was confused for a second given that I just created an airdrop.

Recommendation:
- make it even more obvious that its disabled
- remove completely since user can't click on it anyway
- replace button with one that goes to the distribution page? not clear to me here what is the next step either

<img width="739" alt="Screenshot 2023-03-08 at 2 46 17 PM" src="https://user-images.githubusercontent.com/90453610/223639280-2b047c21-5a5f-4f9c-b3d9-31d2c5603c22.png">

**Comment by parhim** [comment]
it's a result of async checking if the wallet has those options, ill add a loading spinner to that page so it's more obvious that there's a wait

**Comment by parhim** [comment]
added a button to do refresh balances
