### ISSUE TITLE
Not clear what recovering rent does

### ISSUE THREAD

**Issue by iurage** [mithraiclabs/fusion#65]
I minted some options in my wallet that weren't distributed. Does this page mean that I can recover underlying from these undistributed options? Or does it mean that i can recover underlying only from expired options?

Either way its not clear for me and nothing is showing up on this page.

<img width="1382" alt="Screenshot 2023-03-08 at 3 21 16 PM" src="https://user-images.githubusercontent.com/90453610/223647591-9df1c3ac-d11a-4955-b79b-e9c5f554a31c.png">

**Comment by parhim** [comment]
@iurage rent recovery is just the 0.0005 sol for closing the option token account

**Comment by parhim** [comment]
also now you should see everything
