### ISSUE TITLE
No options in wallet were shown in Fusion UI

### ISSUE THREAD

**Issue by iurage** [mithraiclabs/fusion#67]
Is fusion UI supposed to show my other option positions in wallet? Because i am seeing nothing
<img width="869" alt="Screenshot 2023-03-08 at 3 33 37 PM" src="https://user-images.githubusercontent.com/90453610/223649893-176072d9-a20f-40dd-8e54-28446c752153.png">
<img width="1409" alt="Screenshot 2023-03-08 at 3 34 00 PM" src="https://user-images.githubusercontent.com/90453610/223649970-860a31b5-1f04-4ab0-8cd0-a0baa509aab1.png">

**Comment by parhim** [comment]
looks like youre on writer token page, only the dashboard has option tokens
